language: python
dist: focal
sudo: required
cache: pip
python:
  - "3.8"
arch:
  - amd64
  - arm64
addons:
  apt:
    packages:
      - gdb

stages:
  - lint
  - test

jobs:
  include:
    - stage: test
      python: "3.8"
      arch: amd64
    - stage: test
      python: "3.8"
      arch: arm64


before_install:
  - sudo apt-get update
  - sudo apt-get --yes install gdb
  - sudo chmod 777 /proc/sys/kernel/yama/ptrace_scope
  #- sudo sysctl -a
  #- sudo sysctl kernel.version
  #- sudo sysctl kernel.yama.ptrace_scope=1

install:
  - pip install -U pip setuptools tox tox-travis

script:
  - tox -- -n4 -v

env:
  - TOX_SKIP_ENV=.*-cov
