language: python
dist: xenial
sudo: required
cache: pip
python:
  - "3.8"
arch:
  - amd64
  - arm64
addons:
  apt:
    packages:
      - gdb

stages:
  - test

jobs:
  include:
    - stage: test
      python: "3.8"
      env:
        - TOX_SKIP_ENV=.*-cov
      install:
        - sudo sysctl kernel.yama.ptrace_scope=0
        - pip install -U pip setuptools tox tox-travis
      script:
        - tox -- -n4 -v
        
     
    - stage: test
      python: "3.8"
      env:
        - TOX_SKIP_ENV=.*-cov
      arch: arm64
      install:
        - sudo sysctl kernel.yama.ptrace_scope=0
        - pip install -U pip setuptools tox tox-travis
      script:
        - tox -- -n4 -v
