language: python
dist: focal
sudo: required
cache: pip
python:
  - "3.8"
arch:
  - amd64
  - arm64
addons:
  apt:
    packages:
      - gdb

stages:
  - lint
  - test

jobs:
  include:
    - stage: lint
      python: "3.8"
      install:
        - pip install -U pip setuptools flake8
      script:
        - flake8

before_install:
  - sudo apt-get update
  - sudo apt-get --yes install gdb
  - sudo sysctl -a
  - sudo sysctl kernel.version
  - sudo sysctl kernel.yama.ptrace_scope=0

install:
  - pip install -U pip setuptools tox tox-travis

script:
  - tox -- -n4 -v

env:
  - TOX_SKIP_ENV=.*-cov
